---

sudo: true

language: python

python:
  - 2.7

install:
  - pip install ansible==2.1.2

script:
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --become -vvvv
  - >
    ansible-playbook -i inventory playbook.yml --become
    | grep -q 'changed=0.*unreachable=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
