---

- name: Create temporary directory for heka
  tags: heka
  file: dest={{ heka_temp_dir }} mode=0755 state=directory

- name: Download heka
  tags: heka
  get_url:
    dest={{ heka_temp_dir }}/{{ heka_package_filename }}
    url={{ heka_mirror }}/v{{ heka_version }}/{{ heka_package_filename }}

- shell: dpkg -s heka | grep 'install ok'
  tags: heka
  register: heka_state
  ignore_errors: True
  changed_when: False

- name: Install heka
  tags: heka
  command: dpkg -i {{ heka_temp_dir }}/{{ heka_package_filename }}
  when: heka_state|failed

- name: Create Lua directory
  tags: heka
  file: dest={{ heka_lua_dir }} mode=0755 state=directory

- name: Copy monolog.lua
  tags: heka
  copy:
    src=monolog.lua
    dest={{ heka_lua_dir }}/monolog.lua
    owner=0
    group=0
    mode=0644

- name: Install heka configuration
  tags: heka
  template:
    src=main.toml.j2
    dest={{ heka_conf_dir }}/00-hekad.toml
    owner=0
    group=0
    mode=0644

- name: Configure hakad tasks
  tags: heka
  template:
    src=tasks.toml.j2
    dest={{ heka_conf_dir }}/10-tasks.toml
    owner=0
    group=0
    mode=0644

- name: Start heka service
  tags: heka
  changed_when: False
  service: name=heka state=restarted
