---

- name: Create temp folder for heka
  tags: heka
  file: dest={{ heka_ansible_temp_path }} mode=0755 state=directory
  file: dest={{ heka_temp_path }} mode=0755 state=directory

- name: Download heka
  tags: heka
  get_url:
    dest={{ heka_temp_path }}/{{ heka_package_filename }}
    url={{ heka_mirror }}/v{{ heka_version }}/{{ heka_package_filename }}

- shell: dpkg -s heka | grep 'install ok'
  tags: heka
  register: heka_state
  ignore_errors: True
  changed_when: False

- name: Install heka
  tags: heka
  command: dpkg -i {{ heka_temp_path }}/{{ heka_package_filename }}
  when: heka_state|failed

- name: Ensure daemon is present
  tags: heka
  apt: name=daemon state=present

- name: Install hekad service (debian)
  tags: heka
  template:
    src=hekad_initd.j2
    dest=/etc/init.d/hekad
    owner=0
    group=0
    mode=0755

- name: Configure hekad at server startup
  tags: heka
  command: update-rc.d hekad defaults
  when: heka_state|failed

- name: Create directory
  tags: heka
  file: dest={{ heka_hekad_dir }} mode=0755 state=directory

- name: Create Lua directory
  tags: heka
  file: dest={{ heka_hekad_lua_dir }} mode=0755 state=directory

- name: Copy monolog.lua
  tags: heka
  copy:
    src=monolog.lua
    dest={{ heka_hekad_lua_dir }}/monolog.lua
    owner=0
    group=0
    mode=0644

- name: Install hekad configuration
  tags: heka
  template:
    src=heka.toml.j2
    dest={{ heka_hekad_dir }}/0_hekad.toml
    owner=0
    group=0
    mode=0644

- name: Configure hakad
  tags: heka
  template: src=custom.toml.j2 dest={{ heka_hekad_dir }}/10_custom.toml

- name: Start hekad service
  tags: heka
  sudo: true
  changed_when: False
  service: name=hekad state=restarted
